# default config.yml for Bankcraft


database:
#Database in which bankcraft stores information (allowed: flatfile/mysql)
    typeOfDatabase: flatFile
    
    mysql:
        host: 127.0.0.1
        port: 3306
        databaseName: 'mydatabase'
        user: 'Gurke1993'
        password: 'cheesecake'
        
#Import data from the old Bankcraft
    importOldData: false
    
    
general: 
#Maximum ammount of money on players accounts
    maxBankLimitMoney: 50000
    maxBankLimitXp: 50000
    
#Exchangerate for the exchange from money to experience and visa versa
    exchangerateFromMoneyToXp: 0.01
    exchangerateFromXpToMoney: 90
    
    
interest:
#Interest granted on money/experience
    interestOnMoney: 0.0005
    interestOnXp: 0.001
    
#Time until interests are given
    timeBetweenInterestsInMinutes: 2
    
#Should the player get a message if he got interests?
    broadcastMoney: true
    broadcastXp: true
    
#Ingame messages
message:
    createdSignSuccessfully: 'Created sign succesfully!'
    notAllowed: 'You are not allowed to do this!'
    removedSignSuccessfully: 'Sign removed!'
    errorWhileCreatingSign: 'Could not create Sign!'
    balance: '%player2: %balance Dollars!'
    balancexp: '%player2: %balanceXp Experience!'
    amountAddedSuccessfullyToSign: 'Added %amount to Sign!'
    transferedSuccessfully: 'Transfered %amount Dollars from %player to %player2!'
    transferedSuccessfullyXp: 'Transfered %amount Experience from %player to %player2!'
    depositedSuccessfully: 'Deposited %amount Dollar successfully!'
    reachedMaximumMoneyInAccount: 'Reached Accountlimit! (Money)'
    notEnoughMoneyInPoket: 'You dont have %amount money in your pocket!'
    withdrewSuccessfully: 'Withdrew %amount Dollar successfully!'
    reachedMaximumMoneyInPocket: 'Reached Limit of money you can carry around!'
    notEnoughMoneyInAccount: 'You dont have %amount money in your account'
    accountDoesNotExist: 'Account %player2 does not exist!'
    grantedInterestOnMoney: 'You just got %amount Dollar interest on your account!'
    couldNotGrantInterestOnMoney: 'Could not grant interest! Accountlimit reached! (Money)'
    depositedSuccessfullyXp: 'Deposited %amount Experience successfully!'
    reachedMaximumXpInAccount: 'Reached Accountlimit! (XP)'
    notEnoughXpInPoket: 'You dont have %amount xp in your pocket!'
    withdrewSuccessfullyXp: 'Withdrew %amount Experience successfully!'
    reachedMaximumXpInPocket: 'Reached Limit of xp you can carry around!'
    notEnoughXpInAccount: 'You dont have %amount xp in your account'
    grantedInterestOnXp: 'You just got %amount Experience interest on your account!'
    couldNotGrantInterestOnXp: 'Could not grant interest! Accountlimit reached! (XP)'
    exchangedMoneySuccessfully: 'Exchanged %amount money for xp!'
    exchangedXpSuccessfully: 'Exchanged %amount xp for money!'
    interestTimer: 'Interests will be granted in %interestTimeRemaining minutes! Total time: %interestTimeTotal'
    nonExistingInteraction: 'This is not a valid interaction, please choose another.'
    wrongAmountSyntax: 'This is either not a number or an invalid amount, please choose something else.'
    specifyAnInteraction: 'Please type in the Interaction you wish to use.'
    specifyAnAmount: 'Please type in the amount you wish to do.'
    youHaveQuit: 'You have quit the interaction.'

signAndCommand:
    help: help
    balance: balance
    balancexp: balancexp
    deposit: deposit
    withdraw: withdraw
    depositxp: depositxp
    withdrawxp: withdrawxp
    exchange: exchange
    exchangexp: exchangexp
    interesttimer: interesttimer
    chatinteract: chatinteract
    transfer: transfer
    transferxp: transferxp
    signColor: 3
    admin:
        help: help
        clear: clear
        clearxp: clearxp
        set: set
        setxp: setxp
        grant: grant
        grantxp: grantxp
        databaseimport: databaseimport
chat:
#prefix for all Bankcraft messages
    prefix: '[Bankcraft]'
#Color of these
    color: 3
#Word which stops the interaction with a interaction sign
    quit: quit

        
        
        